ssalonen/libcec-sys

.github/workflows/ci.yml

avoid double executions with PRs

---

.github/workflows/ci.yml
scripts/run-bindgen/sed_bindings.py

New derives for enum

---

Cross.toml
scripts/docker/Cross.toml
scripts/docker/Dockerfile
scripts/docker/Makefile
scripts/docker/aarch64-unknown-linux-gnu/Dockerfile
scripts/docker/arm-unknown-linux-gnueabi/Dockerfile
scripts/docker/armv7-unknown-linux-gnueabihf/Dockerfile
scripts/docker/create_dockerfile.sh
scripts/docker/i686-unknown-linux-gnu/Dockerfile
scripts/docker/i686-unknown-linux-musl/Dockerfile
scripts/docker/mips-unknown-linux-gnu/Dockerfile
scripts/docker/mips64-unknown-linux-gnuabi64/Dockerfile
scripts/docker/mips64el-unknown-linux-gnuabi64/Dockerfile
scripts/docker/mipsel-unknown-linux-gnu/Dockerfile
scripts/docker/update_docker_hub_descriptions.sh
scripts/docker/x86_64-pc-windows-gnu/Dockerfile
scripts/docker/x86_64-unknown-linux-gnu/Dockerfile
scripts/docker/x86_64-unknown-linux-musl/Dockerfile

This should bring newer cmake as well, to resolve #5.

Ci update cross docker images

---

CHANGELOG.md

Changelog entry for https://github.com/ssalonen/libcec-sys/pull/6

---

CHANGELOG.md
build.rs

Prep 2.0.1

---

.github/workflows/ci.yml
README.md
build/build.rs

Update `vendor` submodule to latest commit

---

CHANGELOG.md

Added missing changelog entry for #14

---

.github/workflows/ci.yml

CI: utilizing apt patterns

---

CHANGELOG.md
Cargo.toml

Prepare for release (4.0.0)

---

CHANGELOG.md
build/build.rs

Linter fixes

---

CHANGELOG.md
README.md
build/build.rs

Readme clarifications

---

CHANGELOG.md

prep changelog for 4.0.1

---

.github/workflows/ci.yml

Bump python with debug to match github windows runner (3.11.4).

---

.github/workflows/audit.yml
.github/workflows/cd.yml
.github/workflows/ci.yml

Better CI (from ok-nick) rebased

---

CHANGELOG.md
Cargo.toml

Prep 4.0.2 release

---

.github/workflows/ci.yml

CI: Bump up rust-cache

---

CHANGELOG.md
build/build.rs

For https://github.com/ssalonen/cec-rs/pull/41

[WIP] CI Windows: build in defined working directory

---

CHANGELOG.md
Cargo.toml
build/build.rs

Switch to fs_extra provided directory copy

---

CHANGELOG.md
Cargo.toml

Prep for 4.0.3 release

---

README.md

Release guide to bump version after release

---

.github/workflows/ci.yml
docker/Dockerfile-aarch64-unknown-linux-gnu.cross.sccache-from-sources
docker/Dockerfile-x86_64_unknown-linux-gnu.cross.sccache-x86_64-unknown-linux-musl
docker/Dockerfile-x86_64_unknown-linux-musl.cross.sccache-x86_64-unknown-linux-musl

CI: sccache for lint github action

---

Cargo.toml

Unexpected cfg fix

---

src/lib_abi6_x86_64-pc-windows-msvc.rs

Update x86_64-pc-windows-msvc libcec6 bindings

---

src/lib_abi6_x86_64-unknown-linux-gnu.rs

Update x86_64-unknown-linux-gnu libcec6 bindings
